"use client";

import { useState } from "react";
import { FileDown, Loader2 } from "lucide-react";

interface Destination {
  college: string;
  students: string[];
}

interface Props {
  destinations: Destination[];
  totalStudents: number;
  states: number;
}

export default function BrochureButton({ destinations, totalStudents, states }: Props) {
  const [loading, setLoading] = useState(false);

  const download = async () => {
    setLoading(true);
    try {
      const pdfMake = (await import("pdfmake/build/pdfmake")).default;
      const pdfFonts = (await import("pdfmake/build/vfs_fonts")).default;
      pdfMake.vfs = pdfFonts.vfs;

      const docDef = {
        pageSize: "A4" as const,
        pageMargins: [48, 56, 48, 56] as [number, number, number, number],
        content: [
          {
            text: "Nivarro — College Destinations Report",
            style: "header",
            margin: [0, 0, 0, 4] as [number, number, number, number],
          },
          {
            text: `Generated ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
            style: "date",
            margin: [0, 0, 0, 24] as [number, number, number, number],
          },
          {
            columns: [
              { text: [`${totalStudents}\n`, { text: "Students Tracked", style: "statLabel" }], style: "stat" },
              { text: [`${destinations.length}\n`, { text: "Schools", style: "statLabel" }], style: "stat" },
              { text: [`${states}\n`, { text: "States", style: "statLabel" }], style: "stat" },
            ],
            margin: [0, 0, 0, 28] as [number, number, number, number],
          },
          { text: "Destinations by School", style: "sectionTitle", margin: [0, 0, 0, 12] as [number, number, number, number] },
          {
            table: {
              headerRows: 1,
              widths: ["*", "auto", "*"],
              body: [
                [
                  { text: "School", style: "tableHeader" },
                  { text: "Count", style: "tableHeader" },
                  { text: "Students", style: "tableHeader" },
                ],
                ...destinations
                  .sort((a, b) => b.students.length - a.students.length)
                  .map((d) => [
                    { text: d.college, style: "tableCell" },
                    { text: String(d.students.length), style: "tableCell", alignment: "center" },
                    { text: d.students.join(", "), style: "tableCell" },
                  ]),
              ],
            },
            layout: {
              fillColor: (rowIndex: number) => rowIndex === 0 ? "#4a80f0" : rowIndex % 2 === 0 ? "#f5f5f8" : null,
            },
          },
          {
            text: "\nThis report was generated by Nivarro — the student-org matching platform.",
            style: "footer",
            margin: [0, 24, 0, 0] as [number, number, number, number],
          },
        ],
        styles: {
          header: { fontSize: 22, bold: true, color: "#1a1a1f" },
          date: { fontSize: 11, color: "#58586a" },
          stat: { fontSize: 28, bold: true, color: "#4a80f0", alignment: "center" },
          statLabel: { fontSize: 10, color: "#58586a", bold: false },
          sectionTitle: { fontSize: 14, bold: true, color: "#1a1a1f" },
          tableHeader: { fontSize: 11, bold: true, color: "#ffffff" },
          tableCell: { fontSize: 11, color: "#1a1a1f" },
          footer: { fontSize: 10, color: "#909098", italics: true },
        },
        defaultStyle: { font: "Roboto" },
      };

      pdfMake.createPdf(docDef).download("nivarro-college-destinations.pdf");
    } catch (err) {
      console.error("PDF generation failed:", err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={download}
      disabled={loading || destinations.length === 0}
      style={{
        padding: "8px 16px",
        borderRadius: 8,
        border: "1px solid var(--border)",
        background: "var(--n-bg2)",
        color: "var(--text)",
        fontSize: 13,
        fontWeight: 600,
        cursor: loading || destinations.length === 0 ? "not-allowed" : "pointer",
        display: "flex",
        alignItems: "center",
        gap: 6,
        transition: "all 0.15s",
      }}
    >
      {loading ? <Loader2 size={14} style={{ animation: "spin 1s linear infinite" }} /> : <FileDown size={14} />}
      {loading ? "Generating…" : "Download Brochure"}
      <style>{`@keyframes spin { from { transform:rotate(0deg); } to { transform:rotate(360deg); } }`}</style>
    </button>
  );
}
