export const INTEREST_TAG_GROUPS: Record<string, string[]> = {
  "Tech & Engineering": [
    "software development",
    "data science",
    "engineering",
    "robotics",
    "AI/ML",
    "cybersecurity",
    "game development",
    "web design",
  ],
  "Business & Entrepreneurship": [
    "entrepreneurship",
    "startups",
    "finance",
    "marketing",
    "innovation",
    "project management",
    "leadership",
  ],
  "Arts & Media": [
    "performing arts",
    "visual art",
    "music",
    "film",
    "creative writing",
    "photography",
    "journalism",
  ],
  "Social Impact": [
    "community organizing",
    "advocacy",
    "non-profit",
    "education",
    "public policy",
    "environmental justice",
    "healthcare",
  ],
  "Science & Research": [
    "research",
    "biology",
    "chemistry",
    "physics",
    "neuroscience",
    "public health",
    "data analysis",
  ],
  "People & Culture": [
    "public speaking",
    "mentoring",
    "diversity & inclusion",
    "philosophy",
    "psychology",
    "law",
    "history",
  ],
};

export const ALL_INTEREST_TAGS = Object.values(INTEREST_TAG_GROUPS).flat();
