CREATE TABLE IF NOT EXISTS "SavedOrg" (
  "id" TEXT NOT NULL,
  "profileId" TEXT NOT NULL,
  "orgId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SavedOrg_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "SavedOrg_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "SavedOrg_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Org"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "SavedOrg_profileId_orgId_key" ON "SavedOrg"("profileId", "orgId");
